version: '3'

set: [pipefail]

run: when_changed

includes:
  metrics_server: ./src/metrics_server/Taskfile.yml
  sentry_webhook: ./src/sentry_webhook/Taskfile.yml
  shadowbox: ./src/shadowbox/Taskfile.yml

vars:
  ROOT_DIR: "{{.TASKFILE_DIR}}"
  BUILD_DIR: "{{.TASKFILE_DIR}}/build"

tasks:
  clean:
    desc: Clean output files
    cmds:
      - rm -rf .task src/*/node_modules/ build/ node_modules/ third_party/shellcheck/download/ third_party/*/bin third_party/jsign/*.jar
  
  format:
    desc: Format staged files
    cmds: ['npx pretty-quick --staged --pattern "**/*.{cjs,html,js,json,md,ts}"']

  format:all:
    desc: Format all files in the repository
    cmds: ['npx prettier --write "**/*.{cjs,html,js,json,md,ts}"']

  lint:
    desc: Lint all files
    deps: [lint:sh, lint:ts]

  lint:sh:
    desc: Lint all shell files
    cmds: [bash ./scripts/shellcheck.sh]
  
  lint:ts:
    desc: Lint all .ts and .js files
    cmds: ['npx eslint "**/*.{js,ts}"']
  
  test:
    desc: Run all the repository tests
    deps: [lint, metrics_server:test, sentry_webhook:test, shadowbox:test]
