version: "2.1"

networks:
  open:
  censored:

services:
  target:
    build:
      context: ./target
    ports:
      - "10080:80"
    networks:
      - open
    # The python SimpleHTTPServer doesn't quit with SIGTERM.
    stop_signal: SIGKILL

  shadowbox:
    image: ${SB_IMAGE:-outline/shadowbox}
    environment:
      - SB_API_PORT=443
      - SB_API_PREFIX=${SB_API_PREFIX}
      - LOG_LEVEL=debug
      - SB_CERTIFICATE_FILE=/root/shadowbox/test.crt
      - SB_PRIVATE_KEY_FILE=/root/shadowbox/test.key
    ports:
      - "20443:443"
    links:
      - target
    networks:
      - open
      - censored
    volumes:
      - ${SB_CERTIFICATE_FILE}:/root/shadowbox/test.crt
      - ${SB_PRIVATE_KEY_FILE}:/root/shadowbox/test.key
      - ${TMP_STATE_DIR}:/root/shadowbox/persisted-state
    # The user management service doesn't quit with SIGTERM
    stop_signal: SIGKILL

  client:
    build:
      context: ./client
    ports:
      - "30555:555"
    # Keep the container running
    stdin_open: true
    tty: true
    links:
      - shadowbox
    networks:
      - censored

  util:
    build:
      context: ./util
    networks:
      - open
    # Keep the container running
    stdin_open: true
    tty: true
