name: Build and Test - Sentry Webhook

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/sentry_webhook/**'
  push:
    branches:
      - master
    paths:
      - 'src/sentry_webhook/**'

jobs:
  sentry-webhook:
    name: Sentry Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Sentry Webhook Debug Build
        run: npm run action sentry_webhook/build

      - name: Sentry Webhook Test
        run: npm run action sentry_webhook/test
