name: Build and Test - Shadowbox

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/shadowbox/**'
  push:
    branches:
      - master
    paths:
      - 'src/shadowbox/**'

jobs:
  shadowbox:
    name: Shadowbox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install NPM Dependencies
        run: npm ci

      - name: Shadowbox Debug Build
        run: npm run action shadowbox/server/build

      - name: Shadowbox Unit Test
        run: npm run action shadowbox/test

      - name: Shadowbox Integration Test
        run: npm run action shadowbox/integration_test/run

  manual-install-script:
    name: Manual Install Script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Outline Server
        run: ./src/server_manager/install_scripts/install_server.sh --hostname localhost

      - name: Test API
        run: 'curl --silent --fail --insecure $(grep "apiUrl" /opt/outline/access.txt | cut -d: -f 2-)/server'
